/**
 * GingerLive MCP server — Phase P0 (read-only).
 *
 * A stateless Cloudflare Worker (Streamable HTTP at /mcp) that lets any connected AI
 * assistant query GingerLive's public offering. All answers come from a
 * static snapshot (src/data/agent-data.json) generated by the same pipeline that
 * builds llms.txt, so the tools
 * can never drift from the site or expose anything non-public. No auth, no writes in
 * P0 — a campaign-brief write path and OAuth are planned.
 * Each tool call is logged to D1 (USAGE_DB) for coverage analysis; see src/usage.ts.
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { WebStandardStreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js";
import { SUPPORTED_PROTOCOL_VERSIONS } from "@modelcontextprotocol/sdk/types.js";
import { registerGingerLive, SERVER_VERSION } from "./server";
import { d1Sink, type UsageSink } from "./usage";

interface Env {
  USAGE_DB: D1Database;
}

// Sessions without storage. Until Oct 2026 this ran on the Agents SDK's McpAgent, which
// keeps a Durable Object (with its own SQLite database) per MCP session. Registry
// crawlers and directory probes open ~1,500 sessions a day and never close them, so the
// free tier's Durable Objects storage and then rows-written caps were hit. The tools only
// read a bundled snapshot, so nothing needs to persist between requests: every request
// gets a fresh server and transport. To keep the usage log's session id and client name,
// the session id handed out on initialize carries the client's self-reported name and
// version (base64url JSON + random suffix); later requests echo it in mcp-session-id and
// the log decodes it. Unknown or old-format ids are accepted, so no client ever sees
// "Session not found".
interface SessionClient {
  name: string | null;
  version: string | null;
}

const toBase64Url = (text: string) =>
  btoa(String.fromCharCode(...new TextEncoder().encode(text)))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");

const fromBase64Url = (text: string) =>
  new TextDecoder().decode(
    Uint8Array.from(atob(text.replace(/-/g, "+").replace(/_/g, "/")), (c) => c.charCodeAt(0)),
  );

function newSessionId(clientInfo: unknown): string {
  const info = (clientInfo ?? {}) as { name?: unknown; version?: unknown };
  const field = (v: unknown) => (typeof v === "string" ? v.slice(0, 64) : null);
  const random = [...crypto.getRandomValues(new Uint8Array(12))]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return `${toBase64Url(JSON.stringify({ n: field(info.name), v: field(info.version) }))}.${random}`;
}

function clientFromSessionId(sessionId: string | null): SessionClient {
  const encoded = sessionId?.split(".")[0];
  if (!encoded || encoded === sessionId) return { name: null, version: null };
  try {
    const { n, v } = JSON.parse(fromBase64Url(encoded));
    return { name: typeof n === "string" ? n : null, version: typeof v === "string" ? v : null };
  } catch {
    return { name: null, version: null };
  }
}

const mcpCors = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, DELETE, OPTIONS",
  "access-control-allow-headers": "Content-Type, Accept, Authorization, mcp-session-id, mcp-protocol-version, Last-Event-ID",
  "access-control-expose-headers": "mcp-session-id",
  "access-control-max-age": "86400",
};

function withCors(response: Response): Response {
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(mcpCors)) headers.set(k, v);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

async function handleMcp(request: Request, env: Env): Promise<Response> {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: mcpCors });
  // No server-initiated messages, so there is no standalone SSE stream to offer (the
  // spec's answer for that is 405), and nothing to tear down on session DELETE.
  if (request.method === "GET") {
    return new Response(null, { status: 405, headers: { ...mcpCors, allow: "POST, DELETE, OPTIONS" } });
  }
  if (request.method === "DELETE") return new Response(null, { status: 204, headers: mcpCors });

  let body: unknown;
  if (request.method === "POST") {
    try {
      body = await request.json();
    } catch {
      body = undefined; // the transport answers with a JSON-RPC parse error
    }
  }
  const messages = Array.isArray(body) ? body : [body];
  const initialize = messages.find(
    (m): m is { method: string; params?: { clientInfo?: unknown } } =>
      typeof m === "object" && m !== null && (m as { method?: unknown }).method === "initialize",
  );

  const sessionId = initialize ? null : request.headers.get("mcp-session-id");
  const client = clientFromSessionId(sessionId);
  const sink = d1Sink(env.USAGE_DB);
  const logUsage: UsageSink = (event) =>
    sink({
      ...event,
      sessionId: event.sessionId ?? sessionId,
      clientName: event.clientName ?? client.name,
      clientVersion: event.clientVersion ?? client.version,
    });

  const server = new McpServer({ name: "GingerLive", version: SERVER_VERSION });
  registerGingerLive(server, logUsage);
  // Only initialize gets a session id (minted from its clientInfo); everything else runs
  // through a stateless transport, which skips session validation.
  const transport = new WebStandardStreamableHTTPServerTransport({
    sessionIdGenerator: initialize ? () => newSessionId(initialize.params?.clientInfo) : undefined,
  });
  await server.connect(transport);
  return withCors(await transport.handleRequest(request, body === undefined ? undefined : { parsedBody: body }));
}

const HOME = `GingerLive MCP server.

Model Context Protocol endpoint (Streamable HTTP): /mcp
Server card (SEP-2127): /mcp/server-card
Health check: /health
SEP-1960 manifest: /.well-known/mcp
Registry card: /.well-known/mcp.json
Domain discovery (AI Catalog): https://gingerlive.io/.well-known/ai-catalog.json

Read-only tools: get_company_overview, get_network_stats, list_ad_formats,
list_case_studies, get_case_study, get_streamer_program_info.

Human-readable company facts: https://gingerlive.io/llms.txt
Developer resources: https://gingerlive.io/developers/
`;

const MCP_MANIFEST = {
  mcp_version: "1.0",
  server_version: SERVER_VERSION,
  endpoints: {
    streamable_http: "https://mcp.gingerlive.io/mcp",
  },
  capabilities: {
    tools: true,
    resources: true,
    prompts: true,
    sampling: false,
    roots: false,
  },
  authentication: {
    required: false,
    methods: [],
  },
  security: {
    tls_required: true,
    security_contact: "mailto:info@gingerlive.io",
  },
  registration: { dynamic: false },
  documentation: "https://gingerlive.io/developers/",
};

// SEP-2127 (Final) MCP Server Card, per modelcontextprotocol/ext-server-card: identity and
// how to connect, served at <streamable-http-url>/server-card as
// application/mcp-server-card+json. Deliberately identity-only (SEP-2127 cards do not list
// tools; the legacy SEP-1649 catalog on gingerlive.io still does). Protocol versions come
// from the SDK the server negotiates with, so the card cannot drift from runtime behavior.
// Domain-level discovery: https://gingerlive.io/.well-known/ai-catalog.json points here.
const SERVER_CARD = {
  $schema: "https://static.modelcontextprotocol.io/schemas/v1/server-card.schema.json",
  name: "io.gingerlive/mcp",
  version: SERVER_VERSION,
  title: "GingerLive",
  // Same text as server.json (the registry entry): the schema caps it at 100 characters.
  description: "GingerLive livestream ad formats, network reach stats, campaign case studies, and streamer program.",
  websiteUrl: "https://gingerlive.io",
  repository: { url: "https://github.com/gingerlive-io/gingerlive-mcp", source: "github" },
  icons: [
    {
      src: "https://gingerlive.io/Assets/Icons/GingerLiveIcons/squareLogo.png",
      sizes: ["640x640"],
      mimeType: "image/png",
    },
  ],
  remotes: [
    {
      type: "streamable-http",
      url: "https://mcp.gingerlive.io/mcp",
      supportedProtocolVersions: [...SUPPORTED_PROTOCOL_VERSIONS],
    },
  ],
};
const SERVER_CARD_BODY = JSON.stringify(SERVER_CARD, null, 2);
// Strong validator derived from the body (FNV-1a), so it changes whenever the card does.
const SERVER_CARD_ETAG = `"sc-${[...SERVER_CARD_BODY].reduce((h, c) => Math.imul(h ^ c.charCodeAt(0), 16777619) >>> 0, 2166136261).toString(16)}"`;
const serverCardCors = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET",
  "access-control-allow-headers": "Content-Type, If-None-Match",
  "access-control-expose-headers": "ETag",
};

function serveServerCard(request: Request): Response {
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: { ...serverCardCors, "access-control-max-age": "86400" } });
  }
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response(null, { status: 405, headers: { ...serverCardCors, allow: "GET, HEAD, OPTIONS" } });
  }
  const headers = {
    ...serverCardCors,
    "content-type": "application/mcp-server-card+json",
    "cache-control": "public, max-age=3600",
    etag: SERVER_CARD_ETAG,
    "x-content-type-options": "nosniff",
  };
  const ifNoneMatch = request.headers.get("if-none-match");
  if (ifNoneMatch && ifNoneMatch.split(",").some((tag) => tag.trim().replace(/^W\//, "") === SERVER_CARD_ETAG)) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(request.method === "HEAD" ? null : SERVER_CARD_BODY, { headers });
}

const jsonHeaders = {
  "content-type": "application/json; charset=utf-8",
  "x-content-type-options": "nosniff",
  "cache-control": "public, max-age=3600",
  "access-control-allow-origin": "*",
};

export default {
  // Daily cron (wrangler.jsonc): enforce the 12-month retention stated on gingerlive.io/privacy/.
  async scheduled(_controller: ScheduledController, env: Env) {
    await env.USAGE_DB.prepare("DELETE FROM tool_calls WHERE ts < ?")
      .bind(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString())
      .run();
  },

  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ status: "ok", server: "GingerLive", version: SERVER_VERSION });
    }

    if (url.pathname === "/.well-known/mcp" || url.pathname === "/.well-known/mcp.json") {
      return Response.json(url.pathname.endsWith(".json") ? {
        $schema: "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
        name: "io.gingerlive/mcp",
        title: "GingerLive",
        description: "GingerLive livestream ad formats, network reach stats, campaign case studies, and streamer program.",
        version: SERVER_VERSION,
        websiteUrl: "https://gingerlive.io",
        remotes: [{ type: "streamable-http", url: "https://mcp.gingerlive.io/mcp" }],
      } : MCP_MANIFEST, { headers: jsonHeaders });
    }

    if (url.pathname === "/" || url.pathname === "") {
      return new Response(HOME, { headers: { "content-type": "text/plain; charset=utf-8" } });
    }

    // Must precede the /mcp/ transport route below, which would otherwise swallow it.
    if (url.pathname === "/mcp/server-card") {
      return serveServerCard(request);
    }

    // Streamable HTTP transport (recommended for external clients).
    if (url.pathname === "/mcp") {
      return handleMcp(request, env);
    }

    const problem = {
      type: "https://gingerlive.io/developers/#error-not-found",
      title: "Not Found",
      status: 404,
      detail: `No resource at ${url.pathname} on the GingerLive MCP host.`,
      code: "not_found",
      instance: url.pathname,
      hint: "Use POST/GET https://mcp.gingerlive.io/mcp (Streamable HTTP), GET /mcp/server-card, GET /health, or GET /.well-known/mcp. Docs: https://gingerlive.io/developers/",
    };
    return new Response(JSON.stringify(problem, null, 2), {
      status: 404,
      headers: {
        "content-type": "application/problem+json; charset=utf-8",
        "x-content-type-options": "nosniff",
        "access-control-allow-origin": "*",
      },
    });
  },
};
