/**
 * GingerLive MCP server — Phase P0 (read-only).
 *
 * A Cloudflare Worker (Agents SDK `McpAgent`, Streamable HTTP at /mcp) that lets any
 * connected AI assistant query GingerLive's public offering. All answers come from a
 * static snapshot (src/data/agent-data.json) generated by the same pipeline that
 * builds llms.txt, so the tools
 * can never drift from the site or expose anything non-public. No auth, no writes in
 * P0 — a campaign-brief write path and OAuth are planned.
 * Each tool call is logged to D1 (USAGE_DB) for coverage analysis; see src/usage.ts.
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SUPPORTED_PROTOCOL_VERSIONS } from "@modelcontextprotocol/sdk/types.js";
import { McpAgent } from "agents/mcp";
import { registerGingerLive, SERVER_VERSION } from "./server";
import { d1Sink } from "./usage";

interface Env {
  GINGERLIVE_MCP: DurableObjectNamespace;
  USAGE_DB: D1Database;
}

// McpAgent keeps one Durable Object (with its own SQLite storage) per MCP session and
// only deletes it when the client sends a session DELETE — which registry crawlers and
// directory probes never do, so abandoned sessions piled up to the 5 GiB free-tier
// storage cap (Oct 2026). Each session therefore self-destructs after a day without
// requests; a client returning later gets 404 "Session not found" and, per the MCP
// spec, simply re-initializes.
const SESSION_IDLE_SECONDS = 24 * 60 * 60;
// Re-arming the idle timer costs two storage writes, so do it at most hourly per session.
const REARM_INTERVAL_MS = 60 * 60 * 1000;

// Renamed from GingerLiveMCP: the v3 migration deletes that class, wiping the
// abandoned sessions it accumulated (wrangler.jsonc).
export class GingerLiveMCPSession extends McpAgent<Env> {
  server = new McpServer({ name: "GingerLive", version: SERVER_VERSION });
  private idleTimerArmedAt = 0;

  async init() {
    registerGingerLive(this.server, d1Sink(this.env.USAGE_DB));
  }

  // The default event store persists then deletes every response so an SSE stream can
  // be resumed with Last-Event-ID. Our tools answer instantly from static data and the
  // server never pushes notifications, so there is nothing to resume — and those writes
  // were most of the account's daily Durable Objects rows-written usage (free cap 100k).
  protected getEventStore() {
    return undefined;
  }

  // Every MCP request (initialize, POST, GET stream) reaches the session's DO here.
  async fetch(request: Request): Promise<Response> {
    const response = await super.fetch(request);
    try {
      await this.armIdleTimer();
    } catch (err) {
      console.error("Failed to arm session idle timer", err);
    }
    return response;
  }

  // The transport looks the session up here before anything else. A request carrying an
  // unknown or expired session id wakes a fresh DO that would otherwise linger forever
  // after the 404, so arm the timer for it too (a no-op cost for real sessions: their
  // initialize lands here first and the following fetch() is throttled).
  async getInitializeRequest() {
    const initializeRequest = await super.getInitializeRequest();
    if (!initializeRequest) {
      try {
        await this.armIdleTimer();
      } catch (err) {
        console.error("Failed to arm session idle timer", err);
      }
    }
    return initializeRequest;
  }

  private async armIdleTimer() {
    const now = Date.now();
    if (now - this.idleTimerArmedAt < REARM_INTERVAL_MS) return;
    this.idleTimerArmedAt = now;
    for (const s of this.getSchedules()) {
      if (s.callback === "destroyIdleSession") await this.cancelSchedule(s.id);
    }
    await this.schedule(SESSION_IDLE_SECONDS, "destroyIdleSession");
  }

  // Runs only if no request re-armed the timer for SESSION_IDLE_SECONDS.
  async destroyIdleSession() {
    await this.destroy();
  }
}

const HOME = `GingerLive MCP server.

Model Context Protocol endpoint (Streamable HTTP): /mcp
Server card (SEP-2127): /mcp/server-card
Health check: /health
SEP-1960 manifest: /.well-known/mcp
Registry card: /.well-known/mcp.json
Domain discovery (AI Catalog): https://gingerlive.io/.well-known/ai-catalog.json

Read-only tools: get_company_overview, get_network_stats, list_ad_formats,
list_case_studies, get_case_study, get_streamer_program_info.

Human-readable company facts: https://gingerlive.io/llms.txt
Developer resources: https://gingerlive.io/developers/
`;

const MCP_MANIFEST = {
  mcp_version: "1.0",
  server_version: SERVER_VERSION,
  endpoints: {
    streamable_http: "https://mcp.gingerlive.io/mcp",
  },
  capabilities: {
    tools: true,
    resources: true,
    prompts: true,
    sampling: false,
    roots: false,
  },
  authentication: {
    required: false,
    methods: [],
  },
  security: {
    tls_required: true,
    security_contact: "mailto:info@gingerlive.io",
  },
  registration: { dynamic: false },
  documentation: "https://gingerlive.io/developers/",
};

// SEP-2127 (Final) MCP Server Card, per modelcontextprotocol/ext-server-card: identity and
// how to connect, served at <streamable-http-url>/server-card as
// application/mcp-server-card+json. Deliberately identity-only (SEP-2127 cards do not list
// tools; the legacy SEP-1649 catalog on gingerlive.io still does). Protocol versions come
// from the SDK the server negotiates with, so the card cannot drift from runtime behavior.
// Domain-level discovery: https://gingerlive.io/.well-known/ai-catalog.json points here.
const SERVER_CARD = {
  $schema: "https://static.modelcontextprotocol.io/schemas/v1/server-card.schema.json",
  name: "io.gingerlive/mcp",
  version: SERVER_VERSION,
  title: "GingerLive",
  // Same text as server.json (the registry entry): the schema caps it at 100 characters.
  description: "GingerLive livestream ad formats, network reach stats, campaign case studies, and streamer program.",
  websiteUrl: "https://gingerlive.io",
  repository: { url: "https://github.com/gingerlive-io/gingerlive-mcp", source: "github" },
  icons: [
    {
      src: "https://gingerlive.io/Assets/Icons/GingerLiveIcons/squareLogo.png",
      sizes: ["640x640"],
      mimeType: "image/png",
    },
  ],
  remotes: [
    {
      type: "streamable-http",
      url: "https://mcp.gingerlive.io/mcp",
      supportedProtocolVersions: [...SUPPORTED_PROTOCOL_VERSIONS],
    },
  ],
};
const SERVER_CARD_BODY = JSON.stringify(SERVER_CARD, null, 2);
// Strong validator derived from the body (FNV-1a), so it changes whenever the card does.
const SERVER_CARD_ETAG = `"sc-${[...SERVER_CARD_BODY].reduce((h, c) => Math.imul(h ^ c.charCodeAt(0), 16777619) >>> 0, 2166136261).toString(16)}"`;
const serverCardCors = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET",
  "access-control-allow-headers": "Content-Type, If-None-Match",
  "access-control-expose-headers": "ETag",
};

function serveServerCard(request: Request): Response {
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: { ...serverCardCors, "access-control-max-age": "86400" } });
  }
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response(null, { status: 405, headers: { ...serverCardCors, allow: "GET, HEAD, OPTIONS" } });
  }
  const headers = {
    ...serverCardCors,
    "content-type": "application/mcp-server-card+json",
    "cache-control": "public, max-age=3600",
    etag: SERVER_CARD_ETAG,
    "x-content-type-options": "nosniff",
  };
  const ifNoneMatch = request.headers.get("if-none-match");
  if (ifNoneMatch && ifNoneMatch.split(",").some((tag) => tag.trim().replace(/^W\//, "") === SERVER_CARD_ETAG)) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(request.method === "HEAD" ? null : SERVER_CARD_BODY, { headers });
}

const jsonHeaders = {
  "content-type": "application/json; charset=utf-8",
  "x-content-type-options": "nosniff",
  "cache-control": "public, max-age=3600",
  "access-control-allow-origin": "*",
};

export default {
  // Daily cron (wrangler.jsonc): enforce the 12-month retention stated on gingerlive.io/privacy/.
  async scheduled(_controller: ScheduledController, env: Env) {
    await env.USAGE_DB.prepare("DELETE FROM tool_calls WHERE ts < ?")
      .bind(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString())
      .run();
  },

  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ status: "ok", server: "GingerLive", version: SERVER_VERSION });
    }

    if (url.pathname === "/.well-known/mcp" || url.pathname === "/.well-known/mcp.json") {
      return Response.json(url.pathname.endsWith(".json") ? {
        $schema: "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
        name: "io.gingerlive/mcp",
        title: "GingerLive",
        description: "GingerLive livestream ad formats, network reach stats, campaign case studies, and streamer program.",
        version: SERVER_VERSION,
        websiteUrl: "https://gingerlive.io",
        remotes: [{ type: "streamable-http", url: "https://mcp.gingerlive.io/mcp" }],
      } : MCP_MANIFEST, { headers: jsonHeaders });
    }

    if (url.pathname === "/" || url.pathname === "") {
      return new Response(HOME, { headers: { "content-type": "text/plain; charset=utf-8" } });
    }

    // Must precede the /mcp/ transport route below, which would otherwise swallow it.
    if (url.pathname === "/mcp/server-card") {
      return serveServerCard(request);
    }

    // Streamable HTTP transport (recommended for external clients).
    if (url.pathname === "/mcp" || url.pathname.startsWith("/mcp/")) {
      return GingerLiveMCPSession.serve("/mcp", { binding: "GINGERLIVE_MCP" }).fetch(request, env, ctx);
    }

    const problem = {
      type: "https://gingerlive.io/developers/#error-not-found",
      title: "Not Found",
      status: 404,
      detail: `No resource at ${url.pathname} on the GingerLive MCP host.`,
      code: "not_found",
      instance: url.pathname,
      hint: "Use POST/GET https://mcp.gingerlive.io/mcp (Streamable HTTP), GET /mcp/server-card, GET /health, or GET /.well-known/mcp. Docs: https://gingerlive.io/developers/",
    };
    return new Response(JSON.stringify(problem, null, 2), {
      status: 404,
      headers: {
        "content-type": "application/problem+json; charset=utf-8",
        "x-content-type-options": "nosniff",
        "access-control-allow-origin": "*",
      },
    });
  },
};
