/**
 * GingerLive MCP server — Phase P0 (read-only).
 *
 * A Cloudflare Worker (Agents SDK `McpAgent`, Streamable HTTP at /mcp) that lets any
 * connected AI assistant query GingerLive's public offering. All answers come from a
 * static snapshot (src/data/agent-data.json) generated by the same pipeline that
 * builds llms.txt, so the tools
 * can never drift from the site or expose anything non-public. No auth, no writes in
 * P0 — a campaign-brief write path and OAuth are planned.
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { McpAgent } from "agents/mcp";
import { z } from "zod";
import data from "./data/agent-data.json";

interface Env {
  GINGERLIVE_MCP: DurableObjectNamespace;
}

const SERVER_VERSION = "0.2.0";

/** Wrap a JSON-serializable value in the MCP text-result envelope. */
const json = (value: unknown) => ({
  content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }],
});

export class GingerLiveMCP extends McpAgent<Env> {
  server = new McpServer({ name: "GingerLive", version: SERVER_VERSION });

  async init() {
    const company = data.company;

    this.server.registerTool(
      "get_company_overview",
      {
        title: "Company overview",
        description:
          "What GingerLive is: positioning summary, streaming platforms, network stats, third-party measurement partners, and contact links.",
        inputSchema: {},
      },
      async () =>
        json({
          name: company.name,
          summary: company.summary,
          platforms: company.platforms,
          networkStats: data.networkStats,
          measurement: data.measurement,
          contactEmail: company.contactEmail,
          links: company.links,
        }),
    );

    this.server.registerTool(
      "get_network_stats",
      {
        title: "Network stats",
        description:
          "GingerLive's network reach and performance numbers: streamer count, annual unique reach, hours of livestream watched monthly, and ad view-through rate.",
        inputSchema: {},
      },
      async () => json(data.networkStats),
    );

    this.server.registerTool(
      "list_ad_formats",
      {
        title: "Ad formats",
        description:
          "The livestream ad formats GingerLive offers to brands, each with a description, plus the format badges (e.g. unskippable, adblock-safe).",
        inputSchema: {},
      },
      async () => json({ formats: data.adFormats, badges: data.adFormatBadges }),
    );

    this.server.registerTool(
      "list_case_studies",
      {
        title: "List case studies",
        description:
          "GingerLive campaign case studies, each with a short excerpt and a link. Call get_case_study with a slug for the full write-up.",
        inputSchema: {},
      },
      async () =>
        json(
          data.caseStudies.map((s) => ({
            slug: s.slug,
            title: s.title,
            url: s.url,
            date: s.date,
            excerpt: s.excerpt,
          })),
        ),
    );

    this.server.registerTool(
      "get_case_study",
      {
        title: "Get a case study",
        description: "Full write-up for one case study. Pass a slug returned by list_case_studies.",
        inputSchema: {
          slug: z
            .string()
            .describe("Case-study slug, e.g. 'turknet-x-gingerlive-case-study-gen-z-livestream-advertising-campaign'"),
        },
      },
      async ({ slug }) => {
        const study = data.caseStudies.find((s) => s.slug === slug);
        if (!study) {
          return {
            content: [
              {
                type: "text" as const,
                text: `No case study with slug "${slug}". Available slugs: ${data.caseStudies
                  .map((s) => s.slug)
                  .join(", ")}`,
              },
            ],
            isError: true,
          };
        }
        return json({
          slug: study.slug,
          title: study.title,
          url: study.url,
          date: study.date,
          body: study.bodyMarkdown,
        });
      },
    );

    this.server.registerTool(
      "get_streamer_program_info",
      {
        title: "Streamer program",
        description:
          "How a streamer joins and monetizes with GingerLive: cost, how it works, supported platforms, and the sign-up link.",
        inputSchema: {},
      },
      async () => json(data.streamerProgram),
    );

    // --- Resources (grounding) ---
    this.server.resource("company", "gingerlive://company", (uri) => ({
      contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(data.company, null, 2) }],
    }));

    this.server.resource("guides", "gingerlive://guides", (uri) => ({
      contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(data.resourceGuides, null, 2) }],
    }));

    // The canonical llms.txt is served by the origin; expose it live so agents can
    // ground on the single source of truth. Falls back gracefully if unreachable.
    this.server.resource("llms-txt", "https://gingerlive.io/llms.txt", async (uri) => {
      try {
        const res = await fetch("https://gingerlive.io/llms.txt");
        return { contents: [{ uri: uri.href, mimeType: "text/plain", text: await res.text() }] };
      } catch {
        return { contents: [{ uri: uri.href, mimeType: "text/plain", text: "llms.txt is temporarily unavailable." }] };
      }
    });

    // --- Prompts (starting-point templates for clients) ---
    this.server.registerPrompt(
      "plan_livestream_campaign",
      {
        title: "Plan a livestream ad campaign",
        description:
          "Guide the assistant to scope a GingerLive livestream advertising campaign for a brand, using this server's tools.",
        argsSchema: {
          goal: z.string().optional().describe("Campaign goal, e.g. 'reach Gen Z gamers in Turkey'"),
          budget: z.string().optional().describe("Approximate budget or range (optional)"),
        },
      },
      async ({ goal, budget }) => ({
        messages: [
          {
            role: "user",
            content: {
              type: "text",
              text:
                "Help me plan a livestream advertising campaign with GingerLive." +
                (goal ? ` Goal: ${goal}.` : "") +
                (budget ? ` Budget: ${budget}.` : "") +
                " Use the GingerLive tools: get_company_overview and get_network_stats for reach and" +
                " measurement context, list_ad_formats for the format options, and list_case_studies" +
                " (then get_case_study) for comparable results. Then recommend a format mix and next" +
                " steps, and note that a brief can be started at https://gingerlive.io/brands/#contact.",
            },
          },
        ],
      }),
    );

    this.server.registerPrompt(
      "get_started_as_streamer",
      {
        title: "Get started as a GingerLive streamer",
        description:
          "Guide the assistant to help a livestreamer evaluate and join GingerLive's monetization program.",
        argsSchema: {
          platform: z.string().optional().describe("Streaming platform, e.g. Twitch, Kick, YouTube, TikTok"),
        },
      },
      async ({ platform }) => ({
        messages: [
          {
            role: "user",
            content: {
              type: "text",
              text:
                "Help me understand how to monetize my livestreams with GingerLive" +
                (platform ? ` on ${platform}` : "") +
                ". Call get_streamer_program_info for how it works, eligibility and cost, then" +
                " summarize the steps and share the sign-up link.",
            },
          },
        ],
      }),
    );
  }
}

const HOME = `GingerLive MCP server.

Model Context Protocol endpoint (Streamable HTTP): /mcp
Health check: /health
SEP-1960 manifest: /.well-known/mcp
Registry card: /.well-known/mcp.json

Read-only tools: get_company_overview, get_network_stats, list_ad_formats,
list_case_studies, get_case_study, get_streamer_program_info.

Human-readable company facts: https://gingerlive.io/llms.txt
Developer resources: https://gingerlive.io/developers/
`;

const MCP_MANIFEST = {
  mcp_version: "1.0",
  server_version: SERVER_VERSION,
  endpoints: {
    streamable_http: "https://mcp.gingerlive.io/mcp",
  },
  capabilities: {
    tools: true,
    resources: true,
    prompts: true,
    sampling: false,
    roots: false,
  },
  authentication: {
    required: false,
    methods: [],
  },
  security: {
    tls_required: true,
    security_contact: "mailto:info@gingerlive.io",
  },
  registration: { dynamic: false },
  documentation: "https://gingerlive.io/developers/",
};

const jsonHeaders = {
  "content-type": "application/json; charset=utf-8",
  "x-content-type-options": "nosniff",
  "cache-control": "public, max-age=3600",
  "access-control-allow-origin": "*",
};

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ status: "ok", server: "GingerLive", version: SERVER_VERSION });
    }

    if (url.pathname === "/.well-known/mcp" || url.pathname === "/.well-known/mcp.json") {
      return Response.json(url.pathname.endsWith(".json") ? {
        $schema: "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
        name: "io.gingerlive/mcp",
        title: "GingerLive",
        description: "GingerLive livestream ad formats, network reach stats, campaign case studies, and streamer program.",
        version: SERVER_VERSION,
        websiteUrl: "https://gingerlive.io",
        remotes: [{ type: "streamable-http", url: "https://mcp.gingerlive.io/mcp" }],
      } : MCP_MANIFEST, { headers: jsonHeaders });
    }

    if (url.pathname === "/" || url.pathname === "") {
      return new Response(HOME, { headers: { "content-type": "text/plain; charset=utf-8" } });
    }

    // Streamable HTTP transport (recommended for external clients).
    if (url.pathname === "/mcp" || url.pathname.startsWith("/mcp/")) {
      return GingerLiveMCP.serve("/mcp", { binding: "GINGERLIVE_MCP" }).fetch(request, env, ctx);
    }

    const problem = {
      type: "https://gingerlive.io/developers/#error-not-found",
      title: "Not Found",
      status: 404,
      detail: `No resource at ${url.pathname} on the GingerLive MCP host.`,
      code: "not_found",
      instance: url.pathname,
      hint: "Use POST/GET https://mcp.gingerlive.io/mcp (Streamable HTTP), GET /health, or GET /.well-known/mcp. Docs: https://gingerlive.io/developers/",
    };
    return new Response(JSON.stringify(problem, null, 2), {
      status: 404,
      headers: {
        "content-type": "application/problem+json; charset=utf-8",
        "x-content-type-options": "nosniff",
        "access-control-allow-origin": "*",
      },
    });
  },
};
